server:
  port: 8081

spring:
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://localhost:3306/library?createDatabaseIfNotExist=true&characterEncoding=utf8mb4&allowPublicKeyRetrieval=true&useSSL=false
    username:
    password:
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true